# Generated by Django 5.0.7 on 2024-08-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clientCountry', models.CharField(max_length=255)),
                ('clientCity', models.CharField(max_length=255)),
                ('clientRegion', models.CharField(max_length=255)),
                ('clientASN', models.CharField(max_length=255)),
                ('avg_download_speed', models.FloatField()),
                ('avg_upload_speed', models.FloatField()),
                ('avg_latency', models.FloatField()),
            ],
        ),
    ]
