# Generated by Django 5.0.7 on 2024-09-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfricaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clientCountry', models.CharField(max_length=255)),
                ('clientCity', models.CharField(max_length=255)),
                ('clientRegion', models.CharField(max_length=255)),
                ('clientASN', models.CharField(max_length=255)),
                ('avg_download_speed', models.FloatField()),
                ('avg_upload_speed', models.FloatField()),
                ('avg_latency', models.FloatField()),
                ('africa_regions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlab.country')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlab.country')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPerformanceDataNormalized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_download_speed', models.FloatField()),
                ('avg_upload_speed', models.FloatField()),
                ('avg_latency', models.FloatField()),
                ('africa_regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlab.africaregion')),
                ('clientASN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlab.asn')),
                ('clientCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlab.city')),
                ('clientCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlab.country')),
                ('clientRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlab.region')),
            ],
        ),
    ]
