# Generated by Django 5.0.7 on 2024-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipeAtlasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_id', models.IntegerField()),
                ('measurement_id', models.IntegerField()),
                ('result', models.JSONField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
