# Generated by Django 5.0.7 on 2024-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ndt_unified_downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('test_time', models.TimeField()),
                ('throughput', models.FloatField()),
                ('min_rtt', models.FloatField()),
                ('packet_loss', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_radius_km', models.FloatField()),
                ('isp_number', models.IntegerField()),
                ('isp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ndt_unified_uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('test_time', models.TimeField()),
                ('throughput', models.FloatField()),
                ('min_rtt', models.FloatField()),
                ('packet_loss', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_radius_km', models.FloatField()),
                ('isp_number', models.IntegerField()),
                ('isp', models.CharField(max_length=255)),
            ],
        ),
    ]
