# Generated by Django 5.0.7 on 2024-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlab', '0002_ripeatlasdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clientCountry', models.CharField(max_length=255)),
                ('clientASN', models.CharField(max_length=255)),
                ('avg_download_speed', models.FloatField()),
                ('avg_upload_speed', models.FloatField()),
                ('avg_latency', models.FloatField()),
            ],
        ),
    ]
