# Generated by Django 5.0.7 on 2024-09-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlab', '0003_remove_ndt_unified_downloads_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndt_unified_uploads',
            name='date',
        ),
    ]
