# Generated by Django 5.0.7 on 2024-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlab', '0004_remove_ndt_unified_uploads_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndt_unified_downloads',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_downloads',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
