# Generated by Django 5.0.7 on 2024-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlab', '0005_alter_ndt_unified_downloads_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndt_unified_uploads',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_uploads',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
