# Generated by Django 5.0.7 on 2024-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlab', '0007_alter_ndt_unified_downloads_isp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndt_unified_downloads',
            name='accuracy_radius_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_downloads',
            name='isp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_downloads',
            name='min_rtt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_downloads',
            name='packet_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_downloads',
            name='test_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_downloads',
            name='throughput',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_uploads',
            name='accuracy_radius_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_uploads',
            name='isp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_uploads',
            name='min_rtt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_uploads',
            name='packet_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_uploads',
            name='test_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndt_unified_uploads',
            name='throughput',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
